name: cbl_ffi
version: 0.1.0
description: FFI bindings for CouchbaseLite C API and Dart support.
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
