name: cbl_dart
packages:
  - packages/**

scripts:
  formatting:check: melos exec -- dart format --set-exit-if-changed .

  analyze: melos exec -- dart analyze --fatal-infos

  test:all: melos run test:cbl_native && melos run test:cbl && melos run test:standalone_dart

  test:cbl_native:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl_native'

  test:cbl:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl'

  test:standalone_dart:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl_e2e_tests_standalone_dart'

  version:cbl_native:update_lib:
    run: melos exec -- dart run tool/update_version.dart
    select-package:
      scope: 'cbl_native'
