name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  cbl: ^3.0.0-dev.0
  cbl_dart: ^3.0.0-dev.0
  cbl_sentry:
    path: ..
  sentry: ^7.4.2

dev_dependencies:
  flutter_lints: ^2.0.1
