name: 'cbl'
version: 3.4.3
description: >-
  Couchbase Lite is an embedded, NoSQL JSON Document Style database, supporting
  Blobs, Encryption, SQL++ Queries, Live Queries, Full-Text Search and Data
  Sync.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.4.0

dependencies:
  archive: ^4.0.4
  cbl_libcblite_api: ^3.2.0
  cbl_libcblitedart_api: ^8.1.1
  characters: ^1.4.0
  collection: ^1.19.1
  ffi: ^2.1.4
  http: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.1
  stream_channel: ^2.1.4
  synchronized: ^3.3.1
  web_socket_channel: ^3.0.2

dev_dependencies:
  ffigen: ^18.0.0
  test: ^1.25.15
