name: 'cbl_sentry'
version: 1.0.0-beta.2
description: >-
  Sentry integration for Couchbase Lite with support for recording breadcrumbs
  and performance tracing.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_sentry
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cbl: ^1.0.2
  sentry: ^6.3.0

dev_dependencies:
  cbl_dart: ^1.0.0+2
  test: ^1.17.2
