name: cbl_flutter_example
description: Demonstrates how to use the cbl_flutter plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cbl:
    path: ../../cbl
  cbl_flutter:
    path: ../
  path_provider: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

dependency_overrides:
  characters: ^1.1.0

flutter:
  uses-material-design: true
