name: cbl_flutter
description: Binaries required to use cbl in Flutter apps.
version: 0.0.1
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  # cbl: ^0.0.1
  # cbl_flutter_android: ^0.0.1

  cbl:
    path: ../cbl
  cbl_flutter_android:
    path: ../cbl_flutter_android

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CblFlutterPlugin
      macos:
        pluginClass: CblFlutterPlugin
