include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false

linter:
  rules:
    - prefer_relative_imports
    - comment_references
