name: tests-cbl-pkg
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}

      - name: Get flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Get pub dependencies
        run: dart pub get
        working-directory: packages/cbl

      - name: Config CMake build on Linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          CC=clang-10 CXX=clang++-10 cmake \
            -B build \
            -g Ninja \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D CMAKE_INCLUDE_PATH=/usr/lib/llvm-10 \
            .

      - name: Config CMake build on macOS
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          cmake \
            -B build \
            -g Ninja \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            .

      - name: Build binaries with CMake
        run: cmake --build build

      - name: Run tests
        run: dart test -r expanded
        working-directory: packages/cbl
